export enum ActionType {
  RATES_REQUEST = 'RATES_REQUEST',
  RATES_REQUEST_SUCCESS = 'RATES_REQUEST_SUCCESS',

  SOURCE_CURRENCY_CHANGE = 'SOURCE_CURRENCY_CHANGE',
  TARGET_CURRENCY_CHANGE = 'TARGET_CURRENCY_CHANGE'
}
