export enum ActionType {
  RATES_REQUEST = 'RATES_REQUEST',
  RATES_REQUEST_SUCCESS = 'RATES_REQUEST_SUCCESS',
  RATES_REQUEST_FAILURE = 'RATES_REQUEST_FAILURE',

  POCKETS_EXCHANGE = 'POCKETS_EXCHANGE',

  ALERT_ADD = 'ALERT_ADD',
  ALERT_REMOVE = 'ALERT_REMOVE'
}
